CREATE TABLE USERDB (UNAME VARCHAR2(20),UPHNO NUMBER(10) PRIMARY KEY, ULOCATION VARCHAR2(20),UBL_GR VARCHAR2(10),STATUS VARCHAR2(1) CHECK(STATUS IN ('y','n')),LDOD DATE,UPASS VARCHAR2(10),LASTLOGIN VARCHAR2(50));
CREATE TABLE TAGGED (UPHNO NUMBER(10), TAG NUMBER(10), CONSTRAINT c_pk PRIMARY KEY(UPHNO,TAG), FOREIGN KEY(UPHNO) REFERENCES USERDB(UPHNO), FOREIGN KEY(TAG) REFERENCES USERDB(UPHNO));
CREATE TABLE HOSPITALS (HOSID NUMBER(2) PRIMARY KEY,HOSNAME VARCHAR2(20),HOSLOCATION VARCHAR2(20));
CREATE TABLE BLOODBANK (HOSID NUMBER(2)PRIMARY KEY, AP NUMBER,AN NUMBER,BP NUMBER, BN NUMBER, ABP NUMBER, ABN NUMBER, OP NUMBER, ONE NUMBER, FOREIGN KEY(HOSID) REFERENCES HOSPITALS(HOSID));
CREATE TABLE BLOODCAMP (HOSID NUMBER(2), SDATE DATE, EDATE DATE );

INSERT INTO HOSPITALs VALUES(&hid,'&hn','&hl');
INSERT INTO BLOODBANK VALUES(&hid,&ap,&an,&bp,&bn,&abp,&abn,&op,&on);
INSERT INTO BLOODCAMP VALUES(&hid,'&sd','&ed');